Fix import of py_io
The current version of this import makes interrogate fail with an ImportError because there is no definition of "io" in py.py, with interrogate==1.5.0 and py==1.11.0:
```
ImportError: cannot import name 'io' from 'py' 
```